// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwisboqodsjdbnsiywax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53aXNib3FvZHNqZGJuc2l5d2F4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0OTYxODMsImV4cCI6MjA1ODA3MjE4M30.DxKUaz91941e0RnaeEKPEy2w0VuH3rtAxbyZI6izaG0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);